### ISSUE TITLE
Error when generating

### ISSUE THREAD

**Issue by slicksps** [timstokman/YetAnotherTF2ConfigGenerator#1]
I unzipped to desktop and the program worked flawlessly at first. I then moved it into my documents folder out of the way.

Recently after having trouble navigating a demo, I deleted all my configs to reset controls and today went to run the generator again. I loaded the xml and tried to generate but got this error.

http://www.zakomedia.com/error.jpg

I restored my old config backups, I emptied cache folder, I moved it back to the desktop, I tried saving configs locally but keep getting the error and no files are generated.

Nothing has changed on this machine since it was working so it's baffling.

**Comment by timstokman** [comment]
It might be related to your saved settings.xml file, or when moving the program around you may have missed a file or two.

Try:
- Running it without your settings.xml (move it out of the folder)
- Downloading a fresh copy of the program, run it from somewhere else, see if that works

**Comment by timstokman** [comment]
Did that solve things?
