### ISSUE TITLE
Dingaling volume not changing in game.

### ISSUE THREAD

**Issue by Swayyde** [timstokman/YetAnotherTF2ConfigGenerator#3]
When I change the weapon dingaling volume through the program, it doesn't change it in game. If I change it to 3.0, tf_dingaling_volume still says 1.0.

**Comment by timstokman** [comment]
Gonna take a look at this in the weekend

**Comment by timstokman** [comment]
tf_dingaling_volume changes when you change weapons. You can set it per weapon type, so it always changes when you switch weapons, even if you set the general option. Try playing a bit, it should change the volume then. If that doesn't work, contact me on steam, I'll be online a bit 8-9pm london time tomorrow.

**Comment by Swayyde** [comment]
I can't audibly tell a difference when setting it per weapon type so far. The command still shows it as 1.0 regardless as to what weapon is out. It's either not saving or I really need to crank up the number to hear a difference. Not sure yet.

**Comment by timstokman** [comment]
Ah. Partially my fault. The maximum ingame is 1.0. Look at the specification of the function:

"tf_dingaling_volume" ( def. "0.75" ) min. 0.000000 max. 1.000000

So my advice is to raise your volume, and then use values between 0 and 1.

I'll try to patch the application soon, so it gives a warning when you input a value above 1.0.

**Comment by Swayyde** [comment]
Gotcha, gotcha. Thanks for the help.
